### ISSUE TITLE
`plot` fails for `Geometric` distribution

### ISSUE THREAD

**Issue by tomjorquera** [JuliaPlots/StatsPlots.jl#308]
Trying to do

```
plot(Geometric(0.5))
```

fails with 

```
MethodError: no method matching UnitRange(::Int64, ::Float64)
Closest candidates are:
  UnitRange(::T, !Matched::T) where T<:Real at range.jl:279

Stacktrace:
 [1] yz_args(::Geometric{Float64}) at /opt/julia/packages/StatsPlots/dHl9B/src/distributions.jl:25
 [2] macro expansion at /opt/julia/packages/StatsPlots/dHl9B/src/distributions.jl:32 [inlined]
 [3] apply_recipe(::Dict{Symbol,Any}, ::Geometric{Float64}) at /opt/julia/packages/RecipesBase/G4s6f/src/RecipesBase.jl:279
 [4] _process_userrecipes(::Plots.Plot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}, ::Tuple{Geometric{Float64}}) at /opt/julia/packages/Plots/O80o4/src/pipeline.jl:85
 [5] _plot!(::Plots.Plot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}, ::Tuple{Geometric{Float64}}) at /opt/julia/packages/Plots/O80o4/src/plot.jl:178
 [6] #plot#138(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(plot), ::Geometric{Float64}) at /opt/julia/packages/Plots/O80o4/src/plot.jl:57
 [7] plot(::Geometric{Float64}) at /opt/julia/packages/Plots/O80o4/src/plot.jl:51
 [8] top-level scope at In[220]:1
```

`scatter` also fails with the same error.

Other discrete distributions tested (e.g. Binomial, Poisson) are displayed correctly.

Julia version: 1.3.1

Packages versions:
```
  "Distributions"   => v"0.22.4"
  "Plots"           => v"0.29.3"
  "StatsPlots"      => v"0.14.0"
```

**Comment by storopoli** [comment]
Also running with this ERROR while trying `plot(Geometric(0.5))`. All others discrete univariate distributions are OK.

Julia version: 1.5.1

Packages versions:
```
  "Distributions"   => v"0.23.10"
  "Plots"           => v"1.6.0"
  "StatsPlots"      => v"0.12.0"
```

Somehow it's calling the default plot function from the `Plot.jl` package

**Comment by mkborregaard** [comment]
This should be fixed when https://github.com/JuliaStats/Distributions.jl/pull/1169 gets merged.

**Comment by mkborregaard** [comment]
Solved.

**Comment by mkborregaard** [comment]
@storopoli or @tomjorquera would you mind checking (checking out master of Distributions or waiting for 0.23.12) that this is actually resolved to your satisfaction?

**Comment by tomjorquera** [comment]
Strange, the issue seems still present for me.

From a clean env (on julia 1.5.1), I tested the following

```
using Pkg

Pkg.add(url="https://github.com/JuliaStats/Distributions.jl.git", rev="master")
Pkg.add(url="https://github.com/JuliaPlots/StatsPlots.jl.git", rev="master")

using Distributions
using StatsPlots

plot(Geometric(0.5))
```
And still got the same error

```
ERROR: MethodError: no method matching UnitRange(::Int64, ::Float64)
Closest candidates are:
  UnitRange(::T, ::T) where T<:Real at range.jl:282
Stacktrace:
 [1] yz_args(::Geometric{Float64}) at /home/tom/.julia/packages/StatsPlots/cpe0Q/src/distributions.jl:25
 [2] macro expansion at /home/tom/.julia/packages/StatsPlots/cpe0Q/src/distributions.jl:32 [inlined]
 [3] apply_recipe(::Dict{Symbol,Any}, ::Geometric{Float64}) at /home/tom/.julia/packages/RecipesBase/AN696/src/RecipesBase.jl:282
 [4] _process_userrecipes!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Geometric{Float64}}) at /home/tom/.julia/packages/RecipesPipeline/qM4Ea/src/user_recipe.jl:35
 [5] recipe_pipeline!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Geometric{Float64}}) at /home/tom/.julia/packages/RecipesPipeline/qM4Ea/src/RecipesPipeline.jl:69
 [6] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Geometric{Float64}}) at /home/tom/.julia/packages/Plots/M1wcx/src/plot.jl:167
 [7] plot(::Geometric{Float64}; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/tom/.julia/packages/Plots/M1wcx/src/plot.jl:57
 [8] plot(::Geometric{Float64}) at /home/tom/.julia/packages/Plots/M1wcx/src/plot.jl:51
 [9] top-level scope at REPL[28]:1
```

I'm not used to installing specific revisions from github, maybe I did it wrong somehow?

**Comment by storopoli** [comment]
Same here 

```julia
plot(Geometric(0.5))
```

My environment after doing the same installation as @tomjorquera 
```julia
@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [ec485272] ArnoldiMethod v0.0.4
  [6e4b80f9] BenchmarkTools v0.5.0
  [aaaa29a8] Clustering v0.14.1
  [5ae59095] Colors v0.12.4
  [d427f087] CommunityDetection v0.1.0
  [a93c6f00] DataFrames v0.21.7
  [31c24e10] Distributions v0.23.11 `https://github.com/JuliaStats/Distributions.jl.git#master`
  [aa1b3936] GraphIO v0.5.0
  [a2cc645c] GraphPlot v0.3.1
  [b964fa9f] LaTeXStrings v1.1.0
  [093fc24a] LightGraphs v1.3.3
  [7240a794] Oracle v0.1.5
  [91a5bcdd] Plots v1.6.3
  [c3e4b0f8] Pluto v0.11.12
  [7f904dfe] PlutoUI v0.6.1
  [47aef6b3] SimpleWeightedGraphs v1.1.1
  [f3b207a7] StatsPlots v0.14.11 `https://github.com/JuliaPlots/StatsPlots.jl.git#master`
  [2f01184e] SparseArrays
```

**Comment by tomjorquera** [comment]
I can confirm it works great now :+1:

**Comment by mkborregaard** [comment]
great!
